---
title: "Sequential Bayes factor trial design for Gaussian pre-post outcomes"
author:
  - name: André Moser, CTU Bern, University of Bern
    orcid_id: 0000-0001-7178-6539
output: 
  distill::distill_article:
    toc: true
    number_sections: true    
    toc_float: true
bibliography: BFSeqPrePost.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Motivation

The article of @Gajewski2022 discusses a two-stage two-endpoint adaptive Bayesian trial design with a continuous primary endpoint and one secondary endpoint. The novelty of the presented study is that the authors specify rules for early stopping for efficacy or futility based on the posterior distribution for both endpoints jointly with the aim that the analysis for the secondary endpoint has enough information: *"Specifically, we are interested in a trial design that tests success of a single primary endpoint (rank) but with the desire to stop the trial only if the single, key secondary endpoint also has adequate information"* (@Gajewski2022). One limitation of the study from @Gajewski2022 is that the endpoints were defined as the difference between a post-intervention measurement and a pre-intervention measurement. Because of the potential correlation between both measurements there might exist a regression to the mean effect, see for example @Vickers1123. 

@Schonbrodt2018 proposed sequential Bayes factor designs as an alternative to the classic power analysis (Bayesian or Frequentist), which rely on prior guesses of effect sizes and decision cut-offs (for example, cut-offs for posterior predictive distributions or type-I error). The Bayes factor is a compelling alternative to the above mentioned design parameters and allows for sequential update in a trial design. @Schonbrodt2017 defined a sequential Bayes factor (SBF) as a Bayes factor which is computed in a sequential setting until an a priori defined level of evidence is reached.

In the current study we use a sequential Bayes factor design for bivariate Gaussian endpoints to investigate operation characteristics of the implemented trial design and compare it to a Bayesian fixed-n Bayes factor design, a Bayesian design with early stopping rules for efficacy/futility based on posterior predictive distributions and frequentist approaches.